<a href="https://colab.research.google.com/github/saleh1312/python/blob/master/MatrixFactoraization-recomendationSystem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import cv2
import tensorflow.keras.backend as k

In [121]:
data=np.array([[5,2,4,2,1],
               [-1,4,3,1,5],
               [4,-1,-1,2,3],
               [2,3,1,5,3],
               [3,5,-1,-1,-1],
               [-1,5,2,5,5],
               [5,-1,5,-1,4]]).astype(np.float32)

mask=(data>-1)
data =data / 5

In [122]:
y_target=tf.boolean_mask(data, mask)

In [124]:
films=tf.Variable(np.random.uniform(low=0.0, high=1.0, size=(7,5)).astype(np.float32))
films

<tf.Variable 'Variable:0' shape=(7, 5) dtype=float32, numpy=
array([[0.5414501 , 0.20761482, 0.7979041 , 0.48705366, 0.3432371 ],
       [0.26305208, 0.3520349 , 0.55210805, 0.4700298 , 0.1254028 ],
       [0.45689082, 0.3806217 , 0.4938227 , 0.33641848, 0.22209677],
       [0.9742416 , 0.05751273, 0.40599236, 0.7274672 , 0.03373897],
       [0.12381041, 0.4942705 , 0.19637811, 0.49404937, 0.69338566],
       [0.31638527, 0.1694532 , 0.7739914 , 0.04394559, 0.92674416],
       [0.56123614, 0.91142756, 0.6994075 , 0.37577876, 0.11467991]],
      dtype=float32)>

In [125]:
users=tf.Variable(np.random.uniform(low=0.0, high=1.0, size=(7,7)).astype(np.float32))
users

<tf.Variable 'Variable:0' shape=(7, 7) dtype=float32, numpy=
array([[0.6753345 , 0.9091442 , 0.28773135, 0.1553326 , 0.49383196,
        0.09084669, 0.14812168],
       [0.06413612, 0.5541661 , 0.32486966, 0.28466547, 0.80868924,
        0.85941195, 0.90848064],
       [0.6232868 , 0.18379936, 0.7867168 , 0.8553033 , 0.3738321 ,
        0.90490854, 0.6077459 ],
       [0.07935275, 0.5774294 , 0.11546595, 0.77276635, 0.6609811 ,
        0.01235631, 0.23709019],
       [0.39078894, 0.29075584, 0.26809365, 0.01870293, 0.9175325 ,
        0.8051551 , 0.3988286 ],
       [0.6138736 , 0.35677242, 0.23539314, 0.14652227, 0.64612967,
        0.21974854, 0.8952959 ],
       [0.98663455, 0.17338447, 0.06824706, 0.45936385, 0.13494007,
        0.20796175, 0.3196338 ]], dtype=float32)>

In [126]:
opt1 = tf.keras.optimizers.Adam(learning_rate=0.001)
opt2 = tf.keras.optimizers.Adam(learning_rate=0.001)
loss=tf.keras.losses.MeanSquaredError()

In [129]:
def loss3(y_pred):
  # loss for rating values ( that not non )
  y1=tf.boolean_mask(y_pred, mask)
  l=loss(y_target,y1)
  #loss for make sure that the predicted values are between (0-1)
  yy=y_pred.numpy()
  mask2=(yy<0) + (yy>1)
  yt = yy[mask2]
  l2=0
  for i in range(yt.shape[0]):
    if yt[i] <0:
      l2 += np.abs(yt[i]-0)
    if yt[i] >1:
      l2 += np.abs(yt[i]-1)
  return (l+l2)

In [128]:
for e in range(1):
  with tf.GradientTape() as tapef,tf.GradientTape() as tapeu:
    y_pred=tf.matmul(users,films)
    l=loss3(y_pred)
  gf=tapef.gradient(l,films)
  gu=tapeu.gradient(l,users)
  opt1.apply_gradients([(gf, films)]) 
  opt2.apply_gradients([(gu, users)]) 

tf.Tensor(0.6272243, shape=(), dtype=float32)
tf.Tensor(14.617244, shape=(), dtype=float32)


In [107]:
y_pred2=tf.matmul(users,films)

In [117]:
np.round(np.array(y_pred2*5))

array([[5., 2., 4., 4., 1.],
       [4., 4., 3., 1., 5.],
       [4., 3., 2., 2., 3.],
       [2., 3., 1., 5., 3.],
       [3., 5., 3., 3., 4.],
       [4., 5., 2., 5., 5.],
       [5., 4., 5., 3., 4.]], dtype=float32)

In [118]:
data*5

array([[ 5.,  2.,  4.,  4.,  1.],
       [-1.,  4.,  3.,  1.,  5.],
       [ 4., -1., -1.,  2.,  3.],
       [ 2.,  3.,  1.,  5.,  3.],
       [ 3.,  5., -1., -1., -1.],
       [-1.,  5.,  2.,  5.,  5.],
       [ 5., -1.,  5., -1.,  4.]], dtype=float32)

In [30]:
films

<tf.Variable 'Variable:0' shape=(4, 5) dtype=float32, numpy=
array([[ 0.7803039 ,  0.00301696,  0.9268055 ,  0.554033  , -0.19402176],
       [ 0.7640087 ,  0.22431912,  0.2368499 , -0.95948416,  0.51974463],
       [-0.24688153,  0.47026202,  1.0612776 ,  0.29939815,  0.6426111 ],
       [ 0.3338119 ,  0.72327495,  0.01115159,  0.85312814,  0.6183024 ]],
      dtype=float32)>

In [31]:
users

<tf.Variable 'Variable:0' shape=(7, 4) dtype=float32, numpy=
array([[ 0.88876927,  0.14413804, -0.06020005,  0.5438025 ],
       [-0.1792834 ,  0.39600515,  0.6275198 ,  0.5760334 ],
       [-0.38750985,  1.9036046 ,  0.5340571 , -0.6594857 ],
       [ 0.9495229 , -0.06855679,  1.2312821 ,  0.04634057],
       [ 0.3465229 , -0.02025542,  0.25445184,  1.2220329 ],
       [-0.16392809, -0.03481996,  0.5167398 ,  1.0581362 ],
       [ 0.59002894,  0.478593  ,  0.3123135 ,  0.75216186]],
      dtype=float32)>